language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
  - openjdk8
script:
  - mvn clean install --batch-mode --errors -Dinvoker.streamLogsOnFailures=true
  - mvn verify -Pits --batch-mode --errors -Dinvoker.streamLogsOnFailures=true
